name: ci-sonarcloud
on:
  pull_request:
    branches:
      - dev

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.23.5"
      - run: go test -coverprofile=coverage.out
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
